# Generated by Django 5.2.3 on 2026-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_uservote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_named_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
    ]
