# Generated by Django 5.2.3 on 2026-04-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_voteitem_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='vote_limit',
            field=models.IntegerField(default=10),
        ),
    ]
