# Generated by Django 5.2.3 on 2026-04-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_topic_description_topic_is_named_vote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='is_named_vote',
            new_name='is_named',
        ),
    ]
