# Generated by Django 5.2.3 on 2026-04-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_topic_vote_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='vote_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
